# Generated by Django 3.2.6 on 2021-08-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_music_library', '0002_alter_song_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default='Uncatigorized', max_length=50),
        ),
    ]
